### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by MADAO-King** [AyrA/IsEmoji#2]
I have customized a layer of network instead of max pooling, which uses 6 for loops to go through the entire four-dimensional vector to extract features from kernal_size, but the network runs slowly, is there any way to speed up

    for n in range(N):
        for c in range(C):
            for i in range(out_h):
                for j in range(out_w):
                    for p in range(pooling):
                        for q in range(pooling):                                                      # pooling = kernal_size  意思是在pooling区域找最大值
                            max_z[n,c, p, q] = padding_z[n, c, strides * i + p, strides * j + q ]
                    u, s,v = svd(max_z[n, c, :, :])
                    max_p[n, c, :] = max(s)
                    pool_z[n, c, i, j] = max_p[n, c, :]

**Comment by AyrA** [comment]
Wrong repository

**Comment by MADAO-King** [comment]
sorry
